name: Makefile CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: 1.26.x

    - name: Run build and check
      run: make status build fmt vet test

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v9
      with:
        version: v2.12.2
